---
- name: backup | stop service
  ansible.builtin.systemd:
    name: youtrack
    state: stopped

- name: backup | cleanup existing data
  ansible.builtin.file:
    path: "{{ youtrack_data_dir }}"
    state: absent

- name: backup | create data directory
  ansible.builtin.file:
    state: directory
    path: "{{ youtrack_data_dir }}"
    owner: "{{ youtrack_user }}"
    group: "{{ youtrack_group }}"
    mode: 0750

- name: backup | restore youtrack backup from given location
  ansible.builtin.unarchive:
    src: "{{ youtrack_restore_backup_file }}"
    dest: "{{ youtrack_data_dir }}"
    owner: "{{ youtrack_user }}"
    group: "{{ youtrack_group }}"
    remote_src: yes

- name: backup | fix permissions (unarchive doesn't do it properly)
  ansible.builtin.file:
    path: "{{ youtrack_data_dir }}"
    owner: "{{ youtrack_user }}"
    group: "{{ youtrack_group }}"
    recurse: yes

- name: backup | start service
  ansible.builtin.systemd:
    name: youtrack
    state: started
